### PR TITLE
fix: change paint flags to SpannableString in strikethrough prices

### LINKED ISSUE #111: bug: pixelated strikethrough price
**Describe the bug**

Strikethrough price is pixelated

**Steps to reproduce**

**Expected behavior**

Having a non pixelated text

**Screenshots**

image

**Device (please complete the following information):**
- Model: Elo-i3-10Std
- OS: 8.1.0
- Version 27

### PR DESCRIPTION
**Pull request by charlottemougenot**
## Changes description

Change paint flag to SpannableString to have clear text on strikethrough price

## Context

Closes #111 

## Checklist

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [X] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [X] Check your code additions will fail neither code linting checks.
- [X] I have reviewed the submitted code.
- [X] I have tested on a phone device/emulator.
- [X] I have tested on a tablet device/emulator.
- [X] I have tested on a large screen device/emulator.
- [X] If it includes design changes, please ask for a review with a core team designer.

## Does this introduce a breaking change?

- No

## Screenshots
Before : 
image
After : 
image

### CODE REVIEW

**Comment by dktbitrise** [comment]
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/62ac2962b2dd627a/build/2b03faa3-1e9f-4139-a49d-76fb0cce95dd/artifact/5339f44ed27ca506/p/cec7342d4bbd13edd332ba51f1a875e6

File: prices/src/main/java/com/decathlon/vitamin/prices/VitaminPrices.kt [hunk 1]
```diff
@@ -86,6 +92,8 @@ open class VitaminPriceStrikethroughLarge @JvmOverloads constructor(
     defStyleAttr: Int = R.attr.priceStrikethroughLarge
 ) : MaterialTextView(context, attrs, defStyleAttr) {
     init {
-        this.paintFlags = Paint.STRIKE_THRU_TEXT_FLAG
+        val string = SpannableString(this.text)
+        string.setSpan(StrikethroughSpan(), 0, string.length, Spanned.SPAN_EXCLUSIVE_INCLUSIVE)
+        this.text = string
```
Comment (GerardPaligot) [inline prices/src/main/java/com/decathlon/vitamin/prices/VitaminPrices.kt:97]: Maybe we can extract this traitement (and all others) in `foundation` to avoid error in the future?

**Review by GerardPaligot — CHANGES_REQUESTED** [review]

**Comment by dktbitrise** [comment]
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/62ac2962b2dd627a/build/7065e606-89dc-44fa-a507-f271cfc9522c/artifact/a24f67bcdf2c00f9/p/73b1a53dfb6adb8933f06c4d18c519e2

**Review by GerardPaligot — APPROVED** [review]
